[project]
name = "fintools"
version = "1.3.0"
description = "A financial data toolset"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "efinance>=0.5.5.2",
    "limits>=5.6.0",
    "lxml>=6.0.2",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "playwright>=1.57.0",
    "polars>=1.38.1",
    "pyarrow>=23.0.0",
    "pyparsing>=3.3.1",
    "scipy>=1.15.3",
    "setuptools>=80.9.0",
    "stockstats>=0.6.5",
    "tenacity>=9.1.2",
    "tushare>=1.4.24",
    "tzlocal>=5.3.1",
    "wrapt>=2.0.1",
    "yfinance>=0.2.66",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["fintools*"]

[tool.setuptools.package-data]
fintools = ["data/**/*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-q"

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
fintools = { workspace = true, editable = true }

[project.entry-points.'fintools.mcp_services']

[project.optional-dependencies]
mcp = [
    "fastmcp>=2.14.3",
    "langchain-mcp-adapters>=0.2.1",
]
graph = [
    "langgraph>=1.0.4",
]
report = [
    "graphviz>=0.21",
    "matplotlib>=3.10.8",
    "reportlab>=4.4.9",
]

[dependency-groups]
dev = [
    "fastmcp>=2.14.3",
    "fintools",
    "ipython>=8.37.0",
    "langchain>=1.1.3",
    "langchain-mcp-adapters>=0.2.1",
    "langchain-openai>=1.1.1",
    "pytest>=9.0.2",
    "pytest-pythonpath>=0.7.3",
    "pytest-xdist>=3.8.0",
    "watchdog>=6.0.0",
]

